### ISSUE TITLE
purge resulted in following error: "[error] [purge:purge data partition] An error occurred: null"

### ISSUE THREAD

**Issue by janvda** [resin-io-playground/node-red-contrib-resinio#9]
I have deployed application https://github.com/janvda/balena-node-red/tree/pigpiod on my raspberry pi.
When I then trigger the `purge` node then I get the error `An error occurred: null`.
Instead of this I would expect that it deleted all data in my `node-red-data` volume (= mounted under folder `/data` in the `node-red` service).

See here below log file extract:
```
05.10.19 11:30:58 (+0200)  node-red  5 Oct 09:30:58 - [info] 
05.10.19 11:30:58 (+0200)  node-red  
05.10.19 11:30:58 (+0200)  node-red  Welcome to Node-RED
05.10.19 11:30:58 (+0200)  node-red  ===================
05.10.19 11:30:58 (+0200)  node-red  
05.10.19 11:30:58 (+0200)  node-red  5 Oct 09:30:58 - [info] Node-RED version: v1.0.1
05.10.19 11:30:58 (+0200)  node-red  5 Oct 09:30:58 - [info] Node.js  version: v12.7.0
05.10.19 11:30:58 (+0200)  node-red  5 Oct 09:30:58 - [info] Linux 4.14.98 arm LE
05.10.19 11:31:00 (+0200)  node-red  5 Oct 09:31:00 - [info] Loading palette nodes
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] ------------------------------------------------------
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] [node-red-contrib-balena/depDevices] Error: /usr/local/lib/node_modules/node-red-contrib-balena/depDevices/depDevices.html does not exist
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] [node-red-contrib-balena/depApps] Error: /usr/local/lib/node_modules/node-red-contrib-balena/depApps/depApps.html does not exist
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] ------------------------------------------------------
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Settings file  : /usr/src/app/settings.js
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Context store  : 'default' [module=memory]
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] User directory : /data/node-red/user/
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Flows file     : /data/node-red/user/balena_flows.json
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [warn] 
05.10.19 11:31:06 (+0200)  node-red  
05.10.19 11:31:06 (+0200)  node-red  ---------------------------------------------------------------------
05.10.19 11:31:06 (+0200)  node-red  Your flow credentials file is encrypted using a system-generated key.
05.10.19 11:31:06 (+0200)  node-red  
05.10.19 11:31:06 (+0200)  node-red  If the system-generated key is lost for any reason, your credentials
05.10.19 11:31:06 (+0200)  node-red  file will not be recoverable, you will have to delete it and re-enter
05.10.19 11:31:06 (+0200)  node-red  your credentials.
05.10.19 11:31:06 (+0200)  node-red  
05.10.19 11:31:06 (+0200)  node-red  You should set your own key using the 'credentialSecret' option in
05.10.19 11:31:06 (+0200)  node-red  your settings file. Node-RED will then re-encrypt your credentials
05.10.19 11:31:06 (+0200)  node-red  file using your chosen key the next time you deploy a change.
05.10.19 11:31:06 (+0200)  node-red  ---------------------------------------------------------------------
05.10.19 11:31:06 (+0200)  node-red  
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Starting flows
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Started flows
05.10.19 11:31:06 (+0200)  node-red  5 Oct 09:31:06 - [info] Server now running at http://127.0.0.1:1880/
05.10.19 11:33:12 (+0200)  node-red  5 Oct 09:33:12 - [error] [purge:purge data partition] An error occurred: null
05.10.19 11:34:00 (+0200)  node-red  5 Oct 09:34:00 - [error] [purge:purge data partition] An error occurred: null
```

**Comment by janvda** [comment]
FYI my docker-compose.yml file:

```
version: '2'
volumes:
    node-red-data:
services:
  node-red:
    build: ./node-red
    volumes:
      - 'node-red-data:/data'
    restart: always
    privileged: true
    labels:
      io.balena.features.supervisor-api: '1'
    ports:
      - 80:1880  # will make that the balena public URL maps to the node-red editor.
  pigpiod:
    build: ./pigpiod
    restart: always
    privileged: true
    cap_add:
      - SYS_RAWIO  # not sure if this is really needed
    devices:
      # not sure if all below options are really needed.
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c-1:/dev/i2c-1"
    ports:
      # this is only needed in case applications not running on this device also want to connect to
      # this pigpiod daemon.
      - 8888:8888  
```
